### Send POST request with json body
POST http://localhost:3001/lists
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjU4ODI0YTI2ZjFlY2Q1NjEyN2U4OWY1YzkwYTg4MDYxMTJhYmU5OWMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdHJlbGxvLTY5ZjA2IiwiYXVkIjoidHJlbGxvLTY5ZjA2IiwiYXV0aF90aW1lIjoxNjc4ODAwOTIzLCJ1c2VyX2lkIjoiSXRkWHRmd1dTZE5PT1lkdURZY2hWMXI0UTI4MiIsInN1YiI6Ikl0ZFh0ZndXU2ROT09ZZHVEWWNoVjFyNFEyODIiLCJpYXQiOjE2Nzg4MDA5MjMsImV4cCI6MTY3ODgwNDUyMywiZW1haWwiOiJpc2FhYWZAY29kZS5lZHUuYXoiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiaXNhYWFmQGNvZGUuZWR1LmF6Il19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.AFbBwMnF72JIIPOcXdgjJIfAweZgsEH8Ws0HvMmp-6MAhCAHhVvwSLrjhoLUIwlGeD2szCLvn1cQlaXtxUTUDz3fU0XlApo2McA7TktcXRuusKiMem2wOHv54JahANo6p6yLe2btKYKi_IiKuO038mO7e8U51uze3c8SPWNOjUwsKz2hvPBwldSGJa4GgekJyz1QbYZs3iOK471FQi6Yw5wBjrBEWEeHFzNdzzIqtMqozKXu4FKtcMCTmJc5O66N1orMeHzgIKQ9wSUj-_8akq6zNfbYvcCNhW8G7xaRwZCeWkTx5Z0nFctuY-K-n3ocZoCKCsX0Jg21mOA6i9uWzA
Content-Type: application/json

{
  "title": "list1",
  "cards": [],
  "id": "list-1",
  "board_id": "pUsHefcJwIpSypBKnoNm"
}

### Send PUT to list
PUT http://localhost:3001/lists/DDeLJU9rMxRiAVRdLh1O
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjFlOTczZWUwZTE2ZjdlZWY0ZjkyMWQ1MGRjNjFkNzBiMmVmZWZjMTkiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdHJlbGxvLTY5ZjA2IiwiYXVkIjoidHJlbGxvLTY5ZjA2IiwiYXV0aF90aW1lIjoxNjc4ODAwOTIzLCJ1c2VyX2lkIjoiSXRkWHRmd1dTZE5PT1lkdURZY2hWMXI0UTI4MiIsInN1YiI6Ikl0ZFh0ZndXU2ROT09ZZHVEWWNoVjFyNFEyODIiLCJpYXQiOjE2Nzg4MDQ1MDEsImV4cCI6MTY3ODgwODEwMSwiZW1haWwiOiJpc2FhYWZAY29kZS5lZHUuYXoiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiaXNhYWFmQGNvZGUuZWR1LmF6Il19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.LUPQ8YUmoBKTIjyEPEAO3MTuxnx0na1mgXLVkar2CrN7tcFEnwcGWzm_rsdqkth83aJyUc-StljmiFbKwUwi2iBMMyGoTKyhMy55ixVG7YAztkFMH8Zz8nZ6A7uWf06n5qTspZPhA_rcTAb25CoPlQ7GmGaDHiBt-R0-L5_Gz0SYhN3Hq4kNr44DY3pXh1K5FyLJt4VanzEoHIRYLuOcB_EqieM6JwbKxhUzxWipw9vDAPDAtSVpL64eKzlv45XVTMocf4pS8FF4_gP0V1aCnzjsLvvLa41lDa12VoHMhcAa6hvLe75M2EF2BbdtQ-JVYDZrSSbwRFn57IU9iRHp4A
Content-Type: application/json

{
  "title": "list1",
  "cards": [
    {
      "title": "card1",
      "description": "card1 description",
      "id": "card-1",
      "like": "like",
      "comment": "comment"
    },
    {
      "title": "card2",
      "description": "card2 description",
      "id": "card-2",
      "like": "like",
      "comment": "comment"
    }
  ],
  "id": "DDeLJU9rMxRiAVRdLh1O",
  "board_id": "pUsHefcJwIpSypBKnoNm"
}


### Get lists
GET http://localhost:3001/lists
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjFlOTczZWUwZTE2ZjdlZWY0ZjkyMWQ1MGRjNjFkNzBiMmVmZWZjMTkiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdHJlbGxvLTY5ZjA2IiwiYXVkIjoidHJlbGxvLTY5ZjA2IiwiYXV0aF90aW1lIjoxNjc4ODAwOTIzLCJ1c2VyX2lkIjoiSXRkWHRmd1dTZE5PT1lkdURZY2hWMXI0UTI4MiIsInN1YiI6Ikl0ZFh0ZndXU2ROT09ZZHVEWWNoVjFyNFEyODIiLCJpYXQiOjE2Nzg4MDQ1MDEsImV4cCI6MTY3ODgwODEwMSwiZW1haWwiOiJpc2FhYWZAY29kZS5lZHUuYXoiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiaXNhYWFmQGNvZGUuZWR1LmF6Il19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.LUPQ8YUmoBKTIjyEPEAO3MTuxnx0na1mgXLVkar2CrN7tcFEnwcGWzm_rsdqkth83aJyUc-StljmiFbKwUwi2iBMMyGoTKyhMy55ixVG7YAztkFMH8Zz8nZ6A7uWf06n5qTspZPhA_rcTAb25CoPlQ7GmGaDHiBt-R0-L5_Gz0SYhN3Hq4kNr44DY3pXh1K5FyLJt4VanzEoHIRYLuOcB_EqieM6JwbKxhUzxWipw9vDAPDAtSVpL64eKzlv45XVTMocf4pS8FF4_gP0V1aCnzjsLvvLa41lDa12VoHMhcAa6hvLe75M2EF2BbdtQ-JVYDZrSSbwRFn57IU9iRHp4A

### Get lists by board
GET http://localhost:3001/boards/pUsHefcJwIpSypBKnoNm/lists
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjU4ODI0YTI2ZjFlY2Q1NjEyN2U4OWY1YzkwYTg4MDYxMTJhYmU5OWMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdHJlbGxvLTY5ZjA2IiwiYXVkIjoidHJlbGxvLTY5ZjA2IiwiYXV0aF90aW1lIjoxNjc4ODAwOTIzLCJ1c2VyX2lkIjoiSXRkWHRmd1dTZE5PT1lkdURZY2hWMXI0UTI4MiIsInN1YiI6Ikl0ZFh0ZndXU2ROT09ZZHVEWWNoVjFyNFEyODIiLCJpYXQiOjE2Nzg4MDA5MjMsImV4cCI6MTY3ODgwNDUyMywiZW1haWwiOiJpc2FhYWZAY29kZS5lZHUuYXoiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiaXNhYWFmQGNvZGUuZWR1LmF6Il19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.AFbBwMnF72JIIPOcXdgjJIfAweZgsEH8Ws0HvMmp-6MAhCAHhVvwSLrjhoLUIwlGeD2szCLvn1cQlaXtxUTUDz3fU0XlApo2McA7TktcXRuusKiMem2wOHv54JahANo6p6yLe2btKYKi_IiKuO038mO7e8U51uze3c8SPWNOjUwsKz2hvPBwldSGJa4GgekJyz1QbYZs3iOK471FQi6Yw5wBjrBEWEeHFzNdzzIqtMqozKXu4FKtcMCTmJc5O66N1orMeHzgIKQ9wSUj-_8akq6zNfbYvcCNhW8G7xaRwZCeWkTx5Z0nFctuY-K-n3ocZoCKCsX0Jg21mOA6i9uWzA

### Get cards by list
GET http://localhost:3001/lists/DDeLJU9rMxRiAVRdLh1O/cards
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjFlOTczZWUwZTE2ZjdlZWY0ZjkyMWQ1MGRjNjFkNzBiMmVmZWZjMTkiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdHJlbGxvLTY5ZjA2IiwiYXVkIjoidHJlbGxvLTY5ZjA2IiwiYXV0aF90aW1lIjoxNjc4ODAwOTIzLCJ1c2VyX2lkIjoiSXRkWHRmd1dTZE5PT1lkdURZY2hWMXI0UTI4MiIsInN1YiI6Ikl0ZFh0ZndXU2ROT09ZZHVEWWNoVjFyNFEyODIiLCJpYXQiOjE2Nzg4MDQ1MDEsImV4cCI6MTY3ODgwODEwMSwiZW1haWwiOiJpc2FhYWZAY29kZS5lZHUuYXoiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiaXNhYWFmQGNvZGUuZWR1LmF6Il19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.LUPQ8YUmoBKTIjyEPEAO3MTuxnx0na1mgXLVkar2CrN7tcFEnwcGWzm_rsdqkth83aJyUc-StljmiFbKwUwi2iBMMyGoTKyhMy55ixVG7YAztkFMH8Zz8nZ6A7uWf06n5qTspZPhA_rcTAb25CoPlQ7GmGaDHiBt-R0-L5_Gz0SYhN3Hq4kNr44DY3pXh1K5FyLJt4VanzEoHIRYLuOcB_EqieM6JwbKxhUzxWipw9vDAPDAtSVpL64eKzlv45XVTMocf4pS8FF4_gP0V1aCnzjsLvvLa41lDa12VoHMhcAa6hvLe75M2EF2BbdtQ-JVYDZrSSbwRFn57IU9iRHp4A

### Get cards
GET http://localhost:3001/cards
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjFlOTczZWUwZTE2ZjdlZWY0ZjkyMWQ1MGRjNjFkNzBiMmVmZWZjMTkiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vdHJlbGxvLTY5ZjA2IiwiYXVkIjoidHJlbGxvLTY5ZjA2IiwiYXV0aF90aW1lIjoxNjc4ODAwOTIzLCJ1c2VyX2lkIjoiSXRkWHRmd1dTZE5PT1lkdURZY2hWMXI0UTI4MiIsInN1YiI6Ikl0ZFh0ZndXU2ROT09ZZHVEWWNoVjFyNFEyODIiLCJpYXQiOjE2Nzg4MDQ1MDEsImV4cCI6MTY3ODgwODEwMSwiZW1haWwiOiJpc2FhYWZAY29kZS5lZHUuYXoiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiaXNhYWFmQGNvZGUuZWR1LmF6Il19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.LUPQ8YUmoBKTIjyEPEAO3MTuxnx0na1mgXLVkar2CrN7tcFEnwcGWzm_rsdqkth83aJyUc-StljmiFbKwUwi2iBMMyGoTKyhMy55ixVG7YAztkFMH8Zz8nZ6A7uWf06n5qTspZPhA_rcTAb25CoPlQ7GmGaDHiBt-R0-L5_Gz0SYhN3Hq4kNr44DY3pXh1K5FyLJt4VanzEoHIRYLuOcB_EqieM6JwbKxhUzxWipw9vDAPDAtSVpL64eKzlv45XVTMocf4pS8FF4_gP0V1aCnzjsLvvLa41lDa12VoHMhcAa6hvLe75M2EF2BbdtQ-JVYDZrSSbwRFn57IU9iRHp4A
